import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const products = [
  {
    name: "Coursera",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Coursera_logo.svg",
    reviewText: "Courses from top universities.",
    defaultProfit: 10,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "edX",
    image: "https://upload.wikimedia.org/wikipedia/commons/2/20/EdX.svg",
    reviewText: "Advance your career skills.",
    defaultProfit: 11,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Udemy",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/75/Udemy_logo.svg",
    reviewText: "Learn anything from experts.",
    defaultProfit: 14,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Khan Academy",
    image: "https://upload.wikimedia.org/wikipedia/commons/2/21/Khan_Academy_logo.svg",
    reviewText: "Free world-class education.",
    defaultProfit: 8,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Google Classroom",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Google_Classroom_Logo.svg",
    reviewText: "Virtual learning made easy.",
    defaultProfit: 9,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Remini",
    image: "https://play-lh.googleusercontent.com/yCZMNZs0ZQgQ9mYERgu1nGlnOUkFF2UX4PIdM2P16jAAyBMZssLRXw9cAyOZueyBD5w=w240-h480",
    reviewText: "Enhance old or blurry photos.",
    defaultProfit: 12,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Remind",
    image: "https://upload.wikimedia.org/wikipedia/en/6/6b/Remind-logo.png",
    reviewText: "Stay connected with school.",
    defaultProfit: 7,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Robinhood",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Robinhood_Logo_2020.svg",
    reviewText: "Investing made simple.",
    defaultProfit: 20,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Binance",
    image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Binance_Logo.svg",
    reviewText: "Buy and trade crypto securely.",
    defaultProfit: 22,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Trust Wallet",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Trust_Wallet_Logo.png",
    reviewText: "Secure crypto wallet.",
    defaultProfit: 13,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "MetaMask",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/36/MetaMask_Fox.svg",
    reviewText: "Gateway to Web3 apps.",
    defaultProfit: 18,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Coinbase",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Coinbase_App_Icon.png",
    reviewText: "Easy crypto exchange.",
    defaultProfit: 19,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "1Password",
    image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/1Password_Logo.svg",
    reviewText: "Store all your passwords safely.",
    defaultProfit: 14,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "LastPass",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/LastPass_Logo.svg",
    reviewText: "Secure password management.",
    defaultProfit: 10,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Bitwarden",
    image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Bitwarden_Logo_2022.svg",
    reviewText: "Free and secure password storage.",
    defaultProfit: 9,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "McAfee",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b1/McAfee_logo_2021.svg",
    reviewText: "Protect your devices.",
    defaultProfit: 10,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Avast",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Avast_logo_2016.svg",
    reviewText: "Secure your online world.",
    defaultProfit: 11,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "NordVPN",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8b/NordVPN_logo_2021.svg",
    reviewText: "Stay private and secure online.",
    defaultProfit: 12,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "ExpressVPN",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/a3/ExpressVPN_logo.svg",
    reviewText: "Fast and secure browsing.",
    defaultProfit: 13,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Adobe Acrobat",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Adobe_Acrobat_DC_logo_2020.svg",
    reviewText: "View and edit PDFs easily.",
    defaultProfit: 12,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Google Docs",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Google_Docs_logo.svg",
    reviewText: "Create and collaborate online.",
    defaultProfit: 14,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Microsoft Word",
    image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Microsoft_Word_2013-2019_logo.svg",
    reviewText: "Document creation standard.",
    defaultProfit: 15,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Microsoft Excel",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/86/Microsoft_Excel_2013-2019_logo.svg",
    reviewText: "Crunch numbers with ease.",
    defaultProfit: 16,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Google Sheets",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Google_Sheets_logo.svg",
    reviewText: "Collaborative spreadsheets.",
    defaultProfit: 11,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Xender",
    image: "https://upload.wikimedia.org/wikipedia/en/e/e4/Xender_App_Logo.png",
    reviewText: "Share files without data.",
    defaultProfit: 9,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "ShareIt",
    image: "https://upload.wikimedia.org/wikipedia/en/f/f4/ShareIt_Logo.png",
    reviewText: "Quick cross-platform file sharing.",
    defaultProfit: 10,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "MX Player",
    image: "https://upload.wikimedia.org/wikipedia/en/b/b7/MX_Player_Logo.png",
    reviewText: "Play all your videos smoothly.",
    defaultProfit: 8,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "VLC Media Player",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/VLC_icon.svg",
    reviewText: "Versatile media playback.",
    defaultProfit: 7,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Signal",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Signal_Logo.svg",
    reviewText: "Private messaging for everyone.",
    defaultProfit: 9,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Brave Browser",
    image: "https://upload.wikimedia.org/wikipedia/commons/9/96/Brave_logo.svg",
    reviewText: "Private browsing by default.",
    defaultProfit: 10,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "Opera",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Opera_2015_icon.svg",
    reviewText: "Feature-rich alternative browser.",
    defaultProfit: 8,
    defaultDeposit: null,
    isActive: true,
  },
  {
    name: "DuckDuckGo",
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d6/DuckDuckGo_logo.svg/1024px-DuckDuckGo_logo.svg.png",
    reviewText: "Search without being tracked.",
    defaultProfit: 9,
    defaultDeposit: null,
    isActive: true,
  }
];

async function seedProducts() {
  try {
    // await prisma.product.deleteMany();
    await prisma.product.createMany({ data: products });
    console.log("✅ Real-world products seeded successfully!");
  } catch (error) {
    console.error("❌ Error seeding products:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

seedProducts();
